name: Update M3U Playlist

on:
  schedule:
    - cron: "0 * * * *"   # Run every hour at minute 0 UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: powershell/setup-pwsh@v2  # ✅ lowercase 'p'

      - name: Run PowerShell script
        id: run_script
        run: |
          pwsh -Command "
          try {
            ./convert_m3u.ps1 *>&1 | Tee-Object -FilePath logs.txt
            echo 'Script executed successfully'
          } catch {
            Write-Host 'Error occurred running convert_m3u.ps1'
            exit 1
          }"

      - name: Commit and push updated files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Add both output and log files
          git add output.m3u logs.txt
          
          # Only commit if there are actual changes
          git diff --cached --quiet || git commit -m "Auto-update M3U and logs ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
