name: Auto Convert M3U Playlist

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required for push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run M3U conversion script
        shell: pwsh
        run: pwsh ./convert_m3u.ps1

      - name: Commit and push output.m3u if changed
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add output.m3u
          
          if (git diff --cached --quiet) {
            Write-Host "✅ No changes to commit."
          } else {
            git commit -m "Auto update: output.m3u [$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')]"
            git push
            Write-Host "✅ Changes committed and pushed."
          }
