name: Auto Convert M3U Playlist

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v3

      - name: Run conversion script
        shell: pwsh
        run: pwsh ./convert_m3u.ps1

      - name: Commit and push updated output.m3u
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add output.m3u
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Auto update: output.m3u [$(date '+%Y-%m-%d %H:%M:%S')]"
            git push
            echo "✅ Changes committed and pushed."
